### ISSUE TITLE
stuck at "Generating release"

### ISSUE THREAD

**Issue by programisti** [boldpoker/edeliver#160]
Trying to deploy with Edeliver but it gets stuck at Generating release, Ive wait it for 3 hours its totally stuck.
I have did everything as on readme.
Also project contains two submodules (git submodules), may this cause this issue?
this is the result

```
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: root@gtwy.airgateway.net
-----> Resetting remote hosts to 3e6afa96855c42ceb91f8dcb05b68f93d1c94184
-----> Cleaning generated files from last build
-----> Authorizing release store on build host
-----> Fetching / Updating dependencies
-----> Compiling sources
-----> Generating release

```

THis is my .deliver/config

```
APP="ndc-ex-gateway" # name of your release                                                                                                    

BUILD_HOST="gtwy.airgateway.net" # host where to build the release                                                                             
BUILD_USER="root" # local user at build host                                                                                                   
BUILD_AT="gateway" # build directory on build host                                                                                             

STAGING_HOSTS="gtwy.airgateway.net"                                                                                                            
STAGING_USER="root"                                                                                                                            
DELIVER_TO="stage"                                                                                                                             


PRODUCTION_HOSTS="gtwy.airgateway.net" # deploy / production hosts separated by space                                                          
PRODUCTION_USER="root" # local user at deploy hosts                                                                                            
DELIVER_TO="gateway_prod" # build directory on build host                                                                                      
AUTO_VERSION=git-branch+git-revision                                                                                                           

RELEASE_STORE="root@gtwy.airgateway.net:releases"                                                                                              

USING_DISTILLERY='true'                                                                                                                        
```

**Comment by bharendt** [comment]
Yes, fetching git submodules is not done automatically by edeliver. You have to fetch the submodules e.g. in a [`pre_erlang_get_and_update_deps()` pre hook](https://github.com/boldpoker/edeliver/wiki/Run-additional-build-tasks) like this:

```bash
pre_erlang_get_and_update_deps() {
   __sync_remote " # runs the commands on the build host
      [ -f ~/.profile ] && source ~/.profile # load profile (optional)
      set -e # fail if any command fails (recommended)
      cd '$BUILD_AT' # enter the build directory on the build host (required)  
      git submodule update --init # fetch git submodules
   "
}

```

You can also use the edeliver `--verbose` option to get more information why it does not continue to build the release in your case.

**Comment by programisti** [comment]
that does not work
this is output of verbose
```
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: root@gtwy.airgateway.net
Everything up-to-date
-----> Resetting remote hosts to 21672f229e6d4ca2b81ad583f7ac13f30a8964a5
HEAD is now at 21672f2 add submodue udpate code from issue
-----> Cleaning generated files from last build
cleaning files in: .
stdin: is not a tty
Removing _build/
Removing deps/
Removing mix.lock
-----> Authorizing release store on build host
stdin: is not a tty
stdin: is not a tty
-----> Fetching / Updating dependencies
stdin: is not a tty
using mix to fetch and update deps
rebar and rebar3 for mix was built already
* creating /root/.mix/archives/hex-0.13.2
Running dependency resolution
Dependency resolution completed
HERE GOES LIST OF DEPENDENCIES with no errors
-----> Compiling sources
Checking whether deps must be compiled for mix version 1.3.0
stdin: is not a tty
HERE GOES LIST OF DEPENDENCIES WITH NO ERRORS
-----> Generating release
using mix to generate release
stdin: is not a tty
Changed release version from 0.0.1 to 0.0.1+structure-change-21672f2
Building release with MIX_ENV=prod.
Warning: Detected that both, :distillery and :exrm are used as dependency.
         edeliver will use :distillery as build tool unless you remove it 
         as dependency or set the environment variable USING_DISTILLERY='false'.
warning: function elixirc_paths/1 is unused
  mix.exs:31

Warning: Detected that both, :distillery and :exrm are used as dependency.
         edeliver will use :distillery as build tool unless you remove it 
         as dependency or set the environment variable USING_DISTILLERY='false'.

You have dependencies (direct/transitive) which are not in :applications!
The following apps should be added to :applications in mix.exs:

        ibrowse                        => ibrowse is missing from ndc_gateway
        ndc_ex_sdk -> pipe             => pipe is missing from ndc_ex_sdk
        ndc_ex_sdk -> xml_builder_plus => xml_builder_plus is missing from ndc_ex_sdk
        ndc_ex_sdk -> xml_to_keyword   => xml_to_keyword is missing from ndc_ex_sdk
        sweet_xml                      => sweet_xml is missing from ndc_gateway
        poison                         => poison is missing from ndc_gateway
        xml_to_keyword                 => xml_to_keyword is missing from ndc_gateway

Continue anyway? Your release may not work as expected if these dependencies are required! [Yn]: y

** (FunctionClauseError) no function clause matching in Mix.env/1
    (mix) lib/mix.ex:211: Mix.env("prod")
    lib/exrm/utils/utils.ex:19: ReleaseManager.Utils.with_env/2
    lib/mix/tasks/release.ex:164: Mix.Tasks.Release.generate_sys_config/1
    lib/mix/tasks/release.ex:74: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3


A remote command failed on:

  root@gtwy.airgateway.net

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd gateway
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="ndc-ex-gateway" AUTO_VERSION="git-branch+git-revision" BRANCH="structure-change" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix do release.version  --verbose,  release --verbose --env="prod" --name="ndc-ex-gateway"
    fi
  

```

**Comment by bharendt** [comment]
It is recommended to remove `exrm` from the `mix.exs` and the `mix.lock` file when you switch to `distillery` as build tool. But anyway, `USING_DISTILLERY` was not forwarded correctly to the mix tasks on the build host. Maybe you could test the above commit before removing the dependency. Thanks.

**Comment by programisti** [comment]
Ive removed exrm but did not worked

```
-----> Generating release
using mix to generate release
stdin: is not a tty
Changed release version from 0.0.1 to 0.0.1+structure-change-d8d18b6
==> Loading configuration..
==> Assembling release..
==> Failed to build release:
    :no_releases

A remote command failed on:

  root@gtwy.airgateway.net

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd gateway
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="ndc-ex-gateway" AUTO_VERSION="git-branch+git-revision" BRANCH="structure-change" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" mix do release.version  --verbose,  release --verbose --env="prod" --name="ndc-ex-gateway"
    fi

```

**Comment by xurde** [comment]
Hi @bharendt 

This is the output I get while using your patch.

```
==> Assembling release..
==> Failed to build release:
    :no_releases

A remote command failed on:

  root@gtwy.airgateway.net

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd gateway
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="ndc-ex-gateway" AUTO_VERSION="git-branch+git-revision" BRANCH="structure-change" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix do release.version  --verbose,  release --verbose --env="prod" --name="ndc-ex-gateway"
    fi
```

Any clue?
Thanks in advance.

**Comment by bharendt** [comment]
It looks like the release section is [missing](https://github.com/bitwalker/distillery/blob/42de09eee1037d78cfd829a3bc0e85fcfabb5804/lib/mix/lib/releases/assembler.ex#L56) in your `rel/config.exs` __distillery config__ or no default release is set there. Your distillery config should look like this:
```elixir
use Mix.Releases.Config,
    default_release: :"ndc-ex-gateway"
    default_environment: :dev

release :"ndc-ex-gateway" do
  set version: current_version(:"ndc-ex-gateway")
end

```

**Comment by esdras** [comment]
I managed to fix it, for my case at least.

The problem was that the app name in `.deliver/config` didn't match the name of the release in `rel/config.exs`

```
#.deliver/config
APP="appname"
...
```

```
#rel/config.exs
release :appname do
  set version: current_version(:appname)
end

```
Maybe you should ditch the dash from the name of the app?

```
# mix.exs
{:distillery, "~> 0.9", warn_missing: false},
{:edeliver, "~> 1.4"}
```

**Comment by programisti** [comment]
@esdras thanks I tried yes names were different, only difference was _ and - between words
now it changed error it says rel/config not found I need to run release.init but I already did this and rel/config file exists

```
==> You are missing a release config file. Run the release.init task first
```
This is full error message

```
-----> Generating release
using mix to generate release
stdin: is not a tty
Changed release version from 0.0.1 to 0.0.1+deploy-63fcde0
==> Loading configuration..
==> You are missing a release config file. Run the release.init task first

A remote command failed on:

  root@gtwy.airgateway.net

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd gateway
    if [ "mix" = "rebar" ]; then
      echo "using rebar to generate release"
      ./rebar   -f generate
    elif [ "mix" = "relx" ]; then
      echo "using relx to generate release"
      ./relx release
    elif [ "mix" = "mix" ]; then
      echo "using mix to generate release"
      MIX_ENV="prod" LINK_SYS_CONFIG="" LINK_VM_ARGS="" APP="ndc_ex_gateway" AUTO_VERSION="git-branch+git-revision" BRANCH="deploy" SKIP_RELUP_MODIFICATIONS="" RELUP_MODIFICATION_MODULE="" USING_DISTILLERY="true" mix do release.version  --verbose,  release --verbose --env="prod" --name="ndc_ex_gateway"
    fi
```

**Comment by esdras** [comment]
@programisti I have no idea what it might be, did you try to ssh into the remote node and run the build command by hand? Could your rel/config file be listed on .gitignore?

**Comment by robconery** [comment]
@programisti that's distillery telling you to set up a config file. Just run `mix release.init` and it will create a `rel/confix.exs` file that you can then wrestle with for a bit, like I'm doing now :).

**Comment by zazaian** [comment]
Also please ensure that the properly-configured `rel/config.exs` file exists on the branch that you're trying to deploy. If you'd like to deploy a non-master branch, be sure to set the `--branch` flag with the `build` command like this:

```elixir
mix edeliver build release --branch=some-branch
```
