### ISSUE TITLE
module ReleaseManager.Plugin is not loaded and could not be found

### ISSUE THREAD

**Issue by mspanc** [boldpoker/edeliver#22]
I am unable to compile edeliver from master:

```
Compiled lib/edeliver.ex

== Compilation error on file lib/exrm/plugins/link_vm_args.ex ==
** (CompileError) lib/exrm/plugins/link_vm_args.ex:2: module ReleaseManager.Plugin is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/exrm/plugins/link_vm_args.ex:2: ReleaseManager.Plugin.LinkVMARgs (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8


== Compilation error on file lib/exrm/plugins/link_sys_config.ex ==
** (CompileError) lib/exrm/plugins/link_sys_config.ex:2: module ReleaseManager.Plugin is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/exrm/plugins/link_sys_config.ex:2: ReleaseManager.Plugin.LinkSysConfig (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

I've tried to call `mix deps.compile edeliver` and `mix deps.update edeliver` - no success.

**Comment by bharendt** [comment]
It looks like the [exrm](https://github.com/bitwalker/exrm) dependency is missing. 
It is recommendet to use the latest git version of edeliver (not the hex package), because it fixes some issues with recent exrm versions.

**Comment by mspanc** [comment]
It happens with master, not the latest hex package.

**Comment by speeddragon** [comment]
Looks like this issue appesars again with the version 2.10 (released today) of distillery.

```
== Compilation error in file lib/distillery/plugins/modify_relup.ex ==
** (CompileError) lib/distillery/plugins/modify_relup.ex:15: module Mix.Releases.Plugin is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/distillery/plugins/modify_relup.ex:15: Releases.Plugin.ModifyRelup (module)
could not compile dependency :edeliver, "mix compile" failed. You can recompile this dependency with "mix deps.compile edeliver", update it with "mix deps.update edeliver" or clean it with "mix deps.clean edeliver"
```

I've reverted back to 2.0.14 and it works. I don't think they changed the dependencies in the new version of distillery.
